require("config.lazy")
require("base")
require("lsp")
require("autocomplete")
require("git")
require("telescope")
require("gitlab_switcher")

require("rust")
require("javascript")
require("debug_rust")
