return {
    'hrsh7th/nvim-cmp',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-path',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-nvim-lua',
    'hrsh7th/cmp-calc',
    'hrsh7th/cmp-nvim-lsp-signature-help',
    "hrsh7th/cmp-nvim-lsp-document-symbol",
    "petertriho/cmp-git",
    'saadparwaiz1/cmp_luasnip',
    'kristijanhusak/vim-dadbod-completion',
    'L3MON4D3/LuaSnip',
    'onsails/lspkind-nvim',
}