- hosts: localhost
  tasks:

    #- name: Install dotfiles
      #become: yes
      #package:
          #name: lolcat
          #state: present
    - name: Cleanup
      become: no
      shell: |
        rm -rf ~/git/something
        rm -rf ~/.zshrc2
        rm -rf ~/.tmux.conf2
        rm -rf ~/.gitconfig2
    - name: General update
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install dotfiles
      become: no
      shell: |
        cd ~
        mkdir -p git/something && cd git/something
        git clone https://github.com/marcelTau/dotfiles

    - name: Link files
      become: no
      shell: |
        cd ~
        ln git/personal/dotfiles/zsh/zshrc ~/.zshrc2
        ln git/personal/dotfiles/tmux/tmux.conf ~/.tmux.conf2
        ln git/personal/dotfiles/git/.gitconfig ~/.gitconfig2

    - name: Install rust
      become: yes
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install some apps
      become: yes
      shell: |
        npm install -g tldr
        apt install -y bat
        apt install -y tree
        apt install -y tmux
        apt install -y gh
        apt install -y ninja-build
        apt install -y valgrind
        pip3 install icdiff
        cargo install git-delta
        cargo install ripgrep
    - name: Get zsh extensions
      become: no
      shell: |
        git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        git clone https://github.com/unixorn/fzf-zsh-plugin.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin
